name: Publish new branch to Docker Hub

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches: 
      - 'master'
    tags-ignore:
      - 'v*.*.*' # Se salta las versiones etiquetadas

env:
  IMAGE_NAME: mock-web-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract version from Git tag
        id: get_version
        run: echo "version=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

